spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  error:
    include-binding-errors: always
    include-message: always
    include-exception: true
    include-stacktrace: never

jwt:
  token-issuer: bangwidae
  secret-key: secret-key # 나중에 바꿉시당