spring:
  data:
    mongodb:
      uri: ENC(6Q2l9G5xtS6r/FtR6NVIRxwu2g/FXALMOYH3/qxHyPGCxtKELHBOho84z+SyHi+ATsNJuiAzS5QmzQAj+NyEjHgRbn5p6ursl70cz3OpYH7vVo5mXGO3RRTGQy372OPRFL/xL9wJxEbotn7m24Ee7nPGBkuoQhPqxFYR34Jr264=)
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    username: ENC(DEK7lxRAJr3TRo4qNqoW0dIfDt2jpiEdU9Rtxa9khvE63KOPcPsbAkGZsRQQJFNiPbkpKid31MVe+6YcdH9Qrg==)
    password: ENC(5ijBROKTSKxmY1qsM/baCn828AInwh62gpKapzFSntltF7JzNv399MWTboVUTE1Q/07zXD5wTcI0aFZs+JMXrw==)
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    include-binding-errors: always
    include-message: always
    include-exception: true
    include-stacktrace: never

jwt:
  token-issuer: bangwidae
  secret-key: secret-key # 나중에 바꿉시당

map:
  naver:
    authorization:
      client-id: ENC(U1ooxWX24YYjijvwLYvZxHvQ0G00KArWb4BHsPZDYE+m0WtlOVwBKtp0ik0KVKmi)
      client-secret: ENC(ivUwyuZ35N+Du6QSg4/FMxAKdF24PavN75isNr5B696kDTA0sIKf+J0jmaSRRFvp56K42BhunyUNfDqv7iSsjsIC2CgqSGgVSPCbeKxKSlY=)
    host: https://naveropenapi.apigw.ntruss.com

cloud:
  aws:
    end-point: https://kr.object.ncloudstorage.com
    region:
      static: kr-standard
    credentials:
      access-key: ENC(30U1rtUSbQewG+MlWpCAWZO2ve5u18GjiSuhr01EEubrXGGxECcISZLvWXjQSxumcGAIuhGNLF+A2Up/l4Lu3g==)
      secret-key: ENC(UOgpOvh49EqL84zh1eRjBv6uyhqq6F2yWOlK7t6vOd12MgwlyEL0DIO8C7fm1qD5KnalWHYN9whEgD/SSRGmUkhgvryne77x5+quhUfrayU=)
    s3:
      bucket: dori-dori-bucket